name: michaeljdeeb.com
markdown: redcarpet
highlighter: pygments
baseurl: /
url: http://michaeljdeeb.com
permalink: /blog/:title
timezone: America/Minneapolis
paginate: 10
paginate_path: "/blog/page:num"
include: ['/_includes/resume.markdown']
